### PR TITLE
Compile ES6 code on prepublish

### PR DESCRIPTION
**Pull request by mbcrute**
This PR introduces a `precompile` hook that compiles the ES6 code to ES5. This will alleviate issues with tools like `proxyquire` that run _before_ the Babel transpiler and thus crap out when they encounter ES6 code.

### CODE REVIEW

**Comment by mbcrute** [comment]
@lanetix/engineers @scarney81 CR por favor

**Comment by tone81** [comment]
In the PR, I see references to `src`, but there isn't a `src`dir in the repo.

**Comment by scarney81** [comment]
@tone81 `index.js` was moved to `src/index.js`

**Comment by mbcrute** [comment]
@tone https://github.com/lanetix/react-jwt-store/tree/compile-prepublish/src

**Comment by scarney81** [comment]
:sheep:

**Comment by tone81** [comment]
Ah, the move was collapsed on the PR. :credit_card:

**Pull request merged**
