### PR TITLE
lanetix/issues#5547 - Put getting localStorage token in a try/catch exception. The token will then refresh itself.

### PR DESCRIPTION
**Pull request by todesignandconquer**
@lanetix/engineers - CR please. Should truly fix https://github.com/lanetix/ui/pull/1733

### CODE REVIEW

**Comment by taygrave** [comment]
🔑  thanks Damir

**Comment by TyBoss** [comment]
once test threshold is happy 🍏

**Comment by pythonesque** [comment]
👍

**Comment by sahiltalwar88** [comment]
🇬🇧  after CI passes

**Comment by DannyDouglass** [comment]
💪

**Pull request merged**
