### PR TITLE
Don't immediately throw if token isn't present or is invalid

### PR DESCRIPTION
**Pull request by mbcrute**
Currently, if you attempt to initialize this module when no cookie is present (for example, when running tests under Node) or when the cookie has an invalid value it just throws and blows up. This seems suboptimal.

This PR makes this module safe to invoke in these situations. The methods on the store will simply return `undefined` in this case. Also, a warning message will be logged if `console.warn` is available if the token is an invalid value.

Also, standard.

### CODE REVIEW

**Comment by mbcrute** [comment]
@lanetix/engineers Review please

**Comment by pythonesque** [comment]
:+1:, I suppose, as long as this is just for tests.

**Comment by apechimp** [comment]
ohh, IIRC you can work around this by setting `document` to an object as is done in the tests.

**Comment by apechimp** [comment]
haha, I should actually read the code before I respond :frowning: 

Is there anyway to set the cookie in the tests this is failing for?

**Comment by mbcrute** [comment]
@apechimp The issue I'm trying to mitigate is (again) related to getting the React quick create components rendering in the Angular portion of the app. The Karma tests (which run under PhantomJS) immediately crash and burn due to the missing `XSRF-TOKEN` cookie.

Then it occurred to me that maybe `react-jwt-store` shouldn't just completely bomb out if the cookie is missing or isn't a valid JWT. That seems like a bad experience altogether.

**Comment by apechimp** [comment]
Ahh yeah. That makes sense.

:sparkles::sparkles::sparkles::sparkles:
:sparkles:LGTM:sparkles:
:sparkles::sparkles::sparkles::sparkles:

**Pull request merged**
